"""
Diagnostic utilities for GaN-DefectML crystal graphs.

This module provides tools for:
- graph integrity auditing,
- graph topology summaries,
- cutoff-radius comparisons,
- edge-attribute sensitivity tests,
- defect-atom identification,
- local defect-neighborhood inspection,
- and dataset-level graph diagnostics.

These routines are diagnostic only. They do not train models or
generate supervised scientific conclusions.
"""

from __future__ import annotations

from typing import Iterable, Optional

import numpy as np
import pandas as pd
import torch

from .graph_builder import (
    build_periodic_edge_list,
    calculate_bidirectional_fraction,
    summarize_graph,
    validate_graph,
)


# ---------------------------------------------------------------------
# Dataset-level graph validation
# ---------------------------------------------------------------------

def validate_graph_dataset(
    graphs: Iterable,
) -> pd.DataFrame:
    """
    Validate every graph in a graph dataset.

    Returns
    -------
    pandas.DataFrame
        One validation record per configuration.
    """

    records = []

    for graph in graphs:

        validation = validate_graph(
            graph
        )

        records.append(
            {
                "configuration_id":
                    getattr(
                        graph,
                        "configuration_id",
                        None,
                    ),

                "number_of_nodes":
                    int(
                        graph.num_nodes
                    ),

                "number_of_edges":
                    int(
                        graph.num_edges
                    ),

                **validation,
            }
        )

    return pd.DataFrame(
        records
    )


def graph_dataset_is_valid(
    graphs: Iterable,
) -> bool:
    """
    Return True only when every graph passes validation.
    """

    validation_df = (
        validate_graph_dataset(
            graphs
        )
    )

    if validation_df.empty:
        return False

    return bool(
        validation_df[
            "graph_valid"
        ].all()
    )


# ---------------------------------------------------------------------
# Graph topology summaries
# ---------------------------------------------------------------------

def build_graph_summary_table(
    graphs: Iterable,
) -> pd.DataFrame:
    """
    Build graph-level topology and feature summaries.
    """

    records = [
        summarize_graph(
            graph
        )
        for graph in graphs
    ]

    return pd.DataFrame(
        records
    )


def summarize_graph_dataset(
    graphs: Iterable,
) -> dict:
    """
    Generate dataset-level graph statistics.
    """

    graphs = list(
        graphs
    )

    if not graphs:
        raise ValueError(
            "Graph dataset is empty."
        )

    node_counts = np.asarray(
        [
            graph.num_nodes
            for graph in graphs
        ],
        dtype=float,
    )

    edge_counts = np.asarray(
        [
            graph.num_edges
            for graph in graphs
        ],
        dtype=float,
    )

    degrees = (
        edge_counts
        / node_counts
    )

    bidirectional_fractions = (
        np.asarray(
            [
                calculate_bidirectional_fraction(
                    graph
                )
                for graph in graphs
            ],
            dtype=float,
        )
    )

    return {
        "number_of_graphs":
            int(
                len(graphs)
            ),

        "minimum_nodes":
            int(
                node_counts.min()
            ),

        "mean_nodes":
            float(
                node_counts.mean()
            ),

        "maximum_nodes":
            int(
                node_counts.max()
            ),

        "minimum_edges":
            int(
                edge_counts.min()
            ),

        "mean_edges":
            float(
                edge_counts.mean()
            ),

        "maximum_edges":
            int(
                edge_counts.max()
            ),

        "mean_directed_degree":
            float(
                degrees.mean()
            ),

        "mean_bidirectional_fraction":
            float(
                bidirectional_fractions.mean()
            ),
    }


# ---------------------------------------------------------------------
# Cutoff-radius diagnostics
# ---------------------------------------------------------------------

def analyze_structure_cutoff(
    structure,
    cutoff_radius_A: float,
) -> dict:
    """
    Analyze graph topology generated by one cutoff radius.
    """

    (
        edge_index,
        edge_distances,
        _,
    ) = build_periodic_edge_list(
        structure=structure,
        cutoff_radius_A=
            cutoff_radius_A,
    )

    number_of_nodes = len(
        structure
    )

    number_of_edges = (
        edge_index.shape[1]
    )

    if number_of_edges == 0:

        return {
            "cutoff_radius_A":
                float(
                    cutoff_radius_A
                ),

            "number_of_nodes":
                int(
                    number_of_nodes
                ),

            "number_of_edges":
                0,

            "mean_directed_degree":
                0.0,

            "minimum_distance_A":
                np.nan,

            "mean_distance_A":
                np.nan,

            "maximum_distance_A":
                np.nan,
        }

    distances = (
        edge_distances.reshape(
            -1
        )
    )

    return {
        "cutoff_radius_A":
            float(
                cutoff_radius_A
            ),

        "number_of_nodes":
            int(
                number_of_nodes
            ),

        "number_of_edges":
            int(
                number_of_edges
            ),

        "mean_directed_degree":
            float(
                number_of_edges
                / number_of_nodes
            ),

        "minimum_distance_A":
            float(
                distances.min()
            ),

        "mean_distance_A":
            float(
                distances.mean()
            ),

        "maximum_distance_A":
            float(
                distances.max()
            ),
    }


def compare_cutoff_radii(
    structure,
    cutoff_radii_A: Iterable[float] = (
        2.5,
        3.0,
        3.2,
        3.5,
        4.0,
    ),
) -> pd.DataFrame:
    """
    Compare graph topology across candidate cutoff radii.
    """

    records = []

    for cutoff_radius_A in (
        cutoff_radii_A
    ):

        records.append(
            analyze_structure_cutoff(
                structure=structure,
                cutoff_radius_A=
                    float(
                        cutoff_radius_A
                    ),
            )
        )

    return pd.DataFrame(
        records
    )


# ---------------------------------------------------------------------
# Edge-feature sensitivity
# ---------------------------------------------------------------------

@torch.no_grad()
def calculate_edge_attribute_sensitivity(
    model,
    graph_batch,
    device: torch.device,
    replacement: str = "zero",
) -> dict:
    """
    Test whether model predictions respond to edge attributes.

    The original predictions are compared against predictions after
    replacing edge features.

    Parameters
    ----------
    model
        Edge-aware GNN.

    graph_batch
        PyTorch Geometric graph or batch.

    device
        Selected PyTorch device.

    replacement
        ``"zero"`` or ``"mean"``.

    Returns
    -------
    dict
        Mean and maximum absolute prediction changes.
    """

    model = model.to(
        device
    )

    model.eval()

    original_batch = (
        graph_batch.clone().to(
            device
        )
    )

    modified_batch = (
        graph_batch.clone().to(
            device
        )
    )

    original_prediction = (
        model(
            original_batch
        )
        .reshape(
            -1
        )
    )

    if replacement == "zero":

        modified_batch.edge_attr = (
            torch.zeros_like(
                modified_batch.edge_attr
            )
        )

    elif replacement == "mean":

        edge_mean = (
            modified_batch.edge_attr
            .mean(
                dim=0,
                keepdim=True,
            )
        )

        modified_batch.edge_attr = (
            edge_mean.expand_as(
                modified_batch.edge_attr
            )
            .clone()
        )

    else:

        raise ValueError(
            "replacement must be either "
            "'zero' or 'mean'."
        )

    modified_prediction = (
        model(
            modified_batch
        )
        .reshape(
            -1
        )
    )

    absolute_change = torch.abs(
        original_prediction
        - modified_prediction
    )

    return {
        "mean_absolute_output_change":
            float(
                absolute_change
                .mean()
                .item()
            ),

        "maximum_output_change":
            float(
                absolute_change
                .max()
                .item()
            ),

        "edge_attributes_influence_output":
            bool(
                torch.any(
                    absolute_change
                    > 1e-8
                ).item()
            ),

        "original_predictions":
            original_prediction
            .detach()
            .cpu()
            .numpy(),

        "modified_predictions":
            modified_prediction
            .detach()
            .cpu()
            .numpy(),
    }


# ---------------------------------------------------------------------
# Defect atom identification
# ---------------------------------------------------------------------

def identify_inserted_atom(
    pristine_structure,
    defect_structure,
) -> Optional[int]:
    """
    Identify an inserted atom when the defect structure contains
    exactly one additional site.

    This is particularly useful for geometric interstitials.
    """

    if len(
        defect_structure
    ) != (
        len(
            pristine_structure
        )
        + 1
    ):

        return None

    # In the generated structure library, inserted atoms are appended
    # to the structure. Verify the assumption before returning it.
    candidate_index = (
        len(
            defect_structure
        )
        - 1
    )

    return int(
        candidate_index
    )


def identify_removed_species(
    pristine_structure,
    defect_structure,
) -> Optional[str]:
    """
    Identify which elemental species was removed in a vacancy.
    """

    if len(
        defect_structure
    ) != (
        len(
            pristine_structure
        )
        - 1
    ):

        return None

    pristine_counts = (
        pristine_structure
        .composition
        .get_el_amt_dict()
    )

    defect_counts = (
        defect_structure
        .composition
        .get_el_amt_dict()
    )

    for element, count in (
        pristine_counts.items()
    ):

        difference = (
            count
            - defect_counts.get(
                element,
                0
            )
        )

        if np.isclose(
            difference,
            1.0,
        ):

            return element

    return None


def identify_substituted_atom(
    pristine_structure,
    defect_structure,
) -> Optional[int]:
    """
    Identify the substituted site when pristine and defect structures
    have equal atom counts and corresponding coordinates are retained.

    This matches the substitution/antisite generation strategy used
    by the project structure library.
    """

    if len(
        pristine_structure
    ) != len(
        defect_structure
    ):

        return None

    differing_indices = []

    for index, (
        pristine_site,
        defect_site,
    ) in enumerate(
        zip(
            pristine_structure,
            defect_structure,
        )
    ):

        pristine_symbol = (
            pristine_site
            .specie
            .symbol
        )

        defect_symbol = (
            defect_site
            .specie
            .symbol
        )

        if (
            pristine_symbol
            != defect_symbol
        ):

            differing_indices.append(
                index
            )

    if len(
        differing_indices
    ) != 1:

        return None

    return int(
        differing_indices[0]
    )


# ---------------------------------------------------------------------
# Local defect environment
# ---------------------------------------------------------------------

def get_atom_environment(
    structure,
    atom_index: int,
    cutoff_radius_A: float = 3.0,
) -> pd.DataFrame:
    """
    Extract the periodic local neighborhood around one atom.
    """

    if not (
        0
        <= atom_index
        < len(structure)
    ):

        raise IndexError(
            f"Atom index {atom_index} "
            "is outside the structure."
        )

    central_site = (
        structure[
            atom_index
        ]
    )

    neighbors = (
        structure.get_neighbors(
            central_site,
            r=cutoff_radius_A,
            include_index=True,
            include_image=True,
        )
    )

    records = []

    for neighbor in neighbors:

        if (
            neighbor.nn_distance
            <= 1e-8
        ):
            continue

        records.append(
            {
                "central_atom_index":
                    int(
                        atom_index
                    ),

                "central_element":
                    central_site
                    .specie
                    .symbol,

                "neighbor_index":
                    int(
                        neighbor.index
                    ),

                "neighbor_element":
                    neighbor
                    .specie
                    .symbol,

                "distance_A":
                    float(
                        neighbor.nn_distance
                    ),

                "periodic_image":
                    tuple(
                        int(value)
                        for value
                        in neighbor.image
                    ),
            }
        )

    if not records:

        return pd.DataFrame(
            columns=[
                "central_atom_index",
                "central_element",
                "neighbor_index",
                "neighbor_element",
                "distance_A",
                "periodic_image",
            ]
        )

    return (
        pd.DataFrame(
            records
        )
        .sort_values(
            "distance_A"
        )
        .reset_index(
            drop=True
        )
    )


def summarize_atom_environment(
    structure,
    atom_index: int,
    cutoff_radius_A: float = 3.0,
) -> dict:
    """
    Summarize the local chemical environment of one atomic site.
    """

    environment_df = (
        get_atom_environment(
            structure=structure,
            atom_index=atom_index,
            cutoff_radius_A=
                cutoff_radius_A,
        )
    )

    central_site = (
        structure[
            atom_index
        ]
    )

    if environment_df.empty:

        return {
            "atom_index":
                int(
                    atom_index
                ),

            "element":
                central_site
                .specie
                .symbol,

            "number_of_neighbors":
                0,

            "minimum_distance_A":
                np.nan,

            "mean_distance_A":
                np.nan,

            "maximum_distance_A":
                np.nan,
        }

    distances = (
        environment_df[
            "distance_A"
        ]
        .to_numpy(
            dtype=float
        )
    )

    element_counts = (
        environment_df[
            "neighbor_element"
        ]
        .value_counts()
        .to_dict()
    )

    return {
        "atom_index":
            int(
                atom_index
            ),

        "element":
            central_site
            .specie
            .symbol,

        "fractional_coordinates":
            central_site
            .frac_coords
            .tolist(),

        "cartesian_coordinates_A":
            central_site
            .coords
            .tolist(),

        "number_of_neighbors":
            int(
                len(
                    environment_df
                )
            ),

        "minimum_distance_A":
            float(
                distances.min()
            ),

        "mean_distance_A":
            float(
                distances.mean()
            ),

        "maximum_distance_A":
            float(
                distances.max()
            ),

        "neighbor_element_counts":
            element_counts,
    }


# ---------------------------------------------------------------------
# Diagnostic interstitial helper
# ---------------------------------------------------------------------

def diagnose_interstitial_atom(
    pristine_structure,
    interstitial_structure,
    cutoff_radius_A: float = 3.0,
) -> dict:
    """
    Locate and characterize an inserted interstitial atom.

    This reproduces the diagnostic workflow used for configurations
    such as Ga_i_Geo_I_1.
    """

    defect_atom_index = (
        identify_inserted_atom(
            pristine_structure=
                pristine_structure,
            defect_structure=
                interstitial_structure,
        )
    )

    if defect_atom_index is None:

        raise ValueError(
            "Unable to uniquely identify "
            "an inserted interstitial atom."
        )

    site = (
        interstitial_structure[
            defect_atom_index
        ]
    )

    environment_summary = (
        summarize_atom_environment(
            structure=
                interstitial_structure,
            atom_index=
                defect_atom_index,
            cutoff_radius_A=
                cutoff_radius_A,
        )
    )

    return {
        "defect_atom_index":
            int(
                defect_atom_index
            ),

        "element":
            site
            .specie
            .symbol,

        "fractional_coordinates":
            site
            .frac_coords
            .tolist(),

        "cartesian_coordinates_A":
            site
            .coords
            .tolist(),

        "environment":
            environment_summary,
    }
